### ISSUE TITLE
Recipe recursion looping until overflow

### ISSUE THREAD

**Issue by RIPISDRAD** [Sefiraat/EquivalencyTech#1]
https://hastebin.com/qirodareza.properties
and i use java 16
1.16.5
the list of my plugins
![1](https://user-images.githubusercontent.com/76468672/120898869-1fe25580-c642-11eb-8c4c-59134afaa57a.PNG)
![2](https://user-images.githubusercontent.com/76468672/120898873-21138280-c642-11eb-9e6a-1088e25af7b3.PNG)

invisible item frame/ sensible toolbox /beehive add some crafts to the crafting table

**Comment by Sefiraat** [comment]
Invisible item frames added a backward craft. Updated to escape after a certain number of attempts. Crude but works until a better solution is found.
