### ISSUE TITLE
Resource Packs 

### ISSUE THREAD

**Issue by montminyr** [Sefiraat/EquivalencyTech#11]
Hello, 
I was wondering about the support for Resource Packs? I have been able to add custom textures using Slimefun. Although these seem to work if I spawn them through the SF cheat menu only (which I see may not be supported). Crafting/obtaining the items through normal means result in default textures as the custom model data does not get set.

Thanks in advance!

**Comment by Sefiraat** [comment]
EquiTech will son be a slmefun addon so texture support should be native then :)
