### ISSUE TITLE
Crafting recipe is not currently working

### ISSUE THREAD

**Issue by Laughingspade** [Sefiraat/EquivalencyTech#2]
The shaped crafting recipe of Mobius fuel currently does not work as intended yet.

**Comment by Sefiraat** [comment]
As mentioned in the discord message, I will need a copy of any error messages you get in the console while trying to craft and (if there is no error) a copy of the server startup log.

**Comment by Laughingspade** [comment]
No error listed in the console when attempting to craft just is not working as a recipe. Will check next start up

**Comment by Laughingspade** [comment]
![Crafting shown](https://user-images.githubusercontent.com/71941942/120942438-eae40a80-c6f6-11eb-9c06-47e7b77dea49.png)

**Comment by Sefiraat** [comment]
Did you craft the Alchemical Coal or use /sf cheat. /sf cheat will not work for now.

**Comment by Laughingspade** [comment]
I used it for those as a demonstration but normally it didnt work either I will give startup logs to show you.

**Comment by Laughingspade** [comment]
https://pastebin.com/at82icNn (Here is the start up to show it loaded just fine)

**Comment by Sefiraat** [comment]
I might need your server IP to test this as all crafting recipes work by default and you can get the first to work.

**Comment by Laughingspade** [comment]
yeah the first one works for sure my IP is play.trifectamc.net. I am not sure why it does not work

**Comment by Laughingspade** [comment]
Laughingspade#5280
