### ISSUE TITLE
[Issue] -- > plugin won't start

### ISSUE THREAD

**Issue by ScrollDP** [Sefiraat/EquivalencyTech#20]
## Description (Mandatory)

--> The Recipe must have a non-AIR result.

## What caused the issue, what steps led up to the issue (Mandatory)

--> I don't know what causes this problem, but on server where is only slimefun and integrity of server is same, its working fine.

## Log of error, if applicable

[18:18:38 ERROR]: Error occurred while enabling EquivalencyTech v${project.version} (Is it up to date?)
--
2 | java.lang.IllegalArgumentException: Recipe must have non-AIR result.
3 | at com.google.common.base.Preconditions.checkArgument(Preconditions.java:141) ~[patched_1.17.1.jar:git-Purpur-1423]
4 | at org.bukkit.inventory.ShapedRecipe.<init>(ShapedRecipe.java:46) ~[patched_1.17.1.jar:git-Purpur-1423]
5 | at org.bukkit.craftbukkit.v1_17_R1.inventory.CraftShapedRecipe.<init>(CraftShapedRecipe.java:18) ~[patched_1.17.1.jar:git-Purpur-1423]
6 | at org.bukkit.craftbukkit.v1_17_R1.inventory.CraftShapedRecipe.<init>(CraftShapedRecipe.java:22) ~[patched_1.17.1.jar:git-Purpur-1423]
7 | at net.minecraft.world.item.crafting.ShapedRecipe.toBukkitRecipe(ShapedRecipe.java:53) ~[app:?]
8 | at net.minecraft.world.item.crafting.ShapedRecipe.toBukkitRecipe(ShapedRecipe.java:32) ~[app:?]
9 | at org.bukkit.craftbukkit.v1_17_R1.inventory.RecipeIterator.next(RecipeIterator.java:40) ~[patched_1.17.1.jar:git-Purpur-1423]
10 | at org.bukkit.craftbukkit.v1_17_R1.inventory.RecipeIterator.next(RecipeIterator.java:11) ~[patched_1.17.1.jar:git-Purpur-1423]
11 | at org.bukkit.craftbukkit.v1_17_R1.CraftServer.getRecipesFor(CraftServer.java:1441) ~[patched_1.17.1.jar:git-Purpur-1423]
12 | at io.github.sefiraat.equivalencytech.recipes.EmcDefinitions.getEmcValue(EmcDefinitions.java:219) ~[EquivalencyTech - DEV 2 (git 6c267).jar:?]
13 | at io.github.sefiraat.equivalencytech.recipes.EmcDefinitions.fillExtended(EmcDefinitions.java:93) ~[EquivalencyTech - DEV 2 (git 6c267).jar:?]
14 | at io.github.sefiraat.equivalencytech.recipes.EmcDefinitions.<init>(EmcDefinitions.java:51) ~[EquivalencyTech - DEV 2 (git 6c267).jar:?]
15 | at io.github.sefiraat.equivalencytech.EquivalencyTech.onEnable(EquivalencyTech.java:97) ~[EquivalencyTech - DEV 2 (git 6c267).jar:?]
16 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Purpur-1423]
17 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Purpur-1423]
18 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Purpur-1423]
19 | at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Purpur-1423]
20 | at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Purpur-1423]
21 | at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733) ~[patched_1.17.1.jar:git-Purpur-1423]
22 | at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:353) ~[patched_1.17.1.jar:git-Purpur-1423]
23 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[patched_1.17.1.jar:git-Purpur-1423]
24 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1423]
25 | at java.lang.Thread.run(Thread.java:831) ~[?:?]

## Server Type and version (Spigot/Paper etc.)

--> Purpur, the latest build

## Minecraft version

--> 1.17.1

**Comment by Sefiraat** [comment]
Solved on Discord as being due to MagicWands plugin
