### ISSUE TITLE
heads

### ISSUE THREAD

**Issue by RIPISDRAD** [Sefiraat/EquivalencyTech#3]
if u put one ur things on the ground it automatically turn to heads!
latest version 1.16.5
its functionally great as it should
(suggest:dont make it placeable)
16java

**Comment by Sefiraat** [comment]
None of the heads should be placeable. 
can you confirm which head and how you placed it?

**Comment by RIPISDRAD** [comment]
You right click it and the second basic ingredient the first one is made
from 5 coal didn't test this one
The one after this which is 5 of this thing (i am super dumb with names)
the red one
And right click it and done
Btw i got the plugins headsplus
And extra head from sf too 😁 can't see why this is their plugin

**Comment by Sefiraat** [comment]
Derp, i forgot to add this!

Download the newest release (1.1.3) and you should be fine

Sorry

**Comment by RIPISDRAD** [comment]
It's ok man have fun and tnx for the fix
