### ISSUE TITLE
Cannot craft Condensate Chest

### ISSUE THREAD

**Issue by ghost** [Sefiraat/EquivalencyTech#39]
## Description 
When you put the recipe in the crafting table you are not able to craft the condensate chest.

## What caused the issue, what steps led up to the issue 
Make a 1.18.1 paper server
Add the plugin
Start the server
Put the materials in the crafting table

## Log of error, if applicable
N/A

## Server Type and version (Spigot/Paper etc.)
Paper - 187

## Minecraft version
1.18.1

## Plugin version
EquivalencyTech v3

## Sf versions
[03:56:26 INFO]: This Server uses the following setup of Slimefun:
Paper git-Paper-198 (MC: 1.18.1)
Slimefun DEV - 999 (git e02eedd9)
Metrics-Module #28
Java 17

Installed Addons: (34)
  GlobalWarming vDEV - 11 (git 73ff77d4)
  Networks vDEV - 31 (git 773a911c)
  CrystamaeHistoria vDEV - 46 (git 02e6b3f2)
  ExtraTools vDEV - 33 (git 46d26e49)
  AureliumSkills vBeta 1.2.8
  FoxyMachines vDEV - 53 (git 22ddcd9c)
  FNAmplifications vDEV - 44 (git 3b3047fe)
  SimpleMaterialGenerators vDEV - 1 (git 719e1451)
  DynaTech vDEV - 160 (git e1075a1c)
  ExtraGear vDEV - 13 (git c62047e2)
  SFAdvancements vDEV - 8 (git 3f3fd8cc)
  CMILib v1.1.1.0
  InfinityExpansion vDEV - 133 (git c4ba6e16)
  SFCalc vDEV - 37 (git dfc0fc41)
  ElectricSpawners vDEV - 23 (git 6ec96773)
  MobCapturer vDEV - 17 (git c21b00a5)
  SlimyTreeTaps vDEV - 20 (git 963f0383)
  FlowerPower vDEV - 12 (git 8138dc3f)
  SlimeTinker vDEV - 69 (git 4fa5b9d6)
  TranscEndence vDEV - 40 (git cfc98363)
  FluffyMachines vDEV - 101 (git 79408746)
  DyedBackpacks vDEV - 17 (git 8b329e96)
  AlchimiaVitae vDEV - 18 (git 9bafe861)
  HotbarPets vDEV - 38 (git fa6c871d)
  SlimefunLuckyBlocks vDEV - 36 (git 60f0c8dc)
  ExoticGarden vDEV - 78 (git 7f9a5f63)
  DankTech2 vDEV - 4 (git 803760fb)
  Liquid vDEV - 14 (git 0f5346bf)
  SlimeCustomizer vDEV - 23 (git c10380af)
  LiteXpansion vDEV - 168 (git 50536efb)
  ElementManipulation vDEV - 9 (git 4d3ceae6)
  SoulJars vDEV - 23 (git b8358a1f)
  EquivalencyTech v${project.version}
  PotionExpansion vDEV - 5 (git e2cfcd8a)

## Images
![unknown](https://user-images.githubusercontent.com/97077949/155062045-db6e49a0-b386-44b4-8e1a-52dff77ebc4a.png)
![unknown](https://user-images.githubusercontent.com/97077949/155062058-934212e4-4942-4db4-ae61-65e54ef6ff85.png)

**Comment by ghost** [comment]
Just realized the build on spigot page was outdated I guess , lemme download the GitHub one and ill get back to you.
Edit - Still doesn't work even in version 3

**Comment by PhoenixCodingStuff** [comment]
Boomer said that this and EMC2 are being compiled into a new plugin so I will wait for that

**Comment by ghost** [comment]
well since this is dead , I will close this issue
