### ISSUE TITLE
1.17 stalls on startup

### ISSUE THREAD

**Issue by thiccz1** [Sefiraat/EquivalencyTech#4]
https://pastebin.com/RhRudUgr

**Comment by Sefiraat** [comment]
Thanks thic,

It's getting stuck in an endless recipe loop, which I had thought shouldn't happen regardless of the new version.

Can you please change the Config.yml value : DEBUG.SHOW_DEBUGGING_LOGS from false to true and then try to run the server again. It will SPAM your logs and you should see it begin to loop. When this happens, kill start up and pastebin your latest.log file contents.

**Comment by thiccz1** [comment]
https://pastebin.com/ru4RyrGP It just continues with all the new raw ore blocks and raw ores

**Comment by thiccz1** [comment]
couldn't actually paste it all because of pastebin limits

**Comment by Sefiraat** [comment]
Ok, in releases, check out 1.1.5-SNAPSHOT.
Let me know how you get on with it.

**Comment by thiccz1** [comment]
ok so it starts fine now but now i have the problem of the transmutation orb not opening

**Comment by Sefiraat** [comment]
Any messages any feedback?

**Comment by thiccz1** [comment]
sends this debug message whenever i try to open it https://pastebin.com/GPrVn2ar

**Comment by Sefiraat** [comment]
Right, i've gone through it and we need to wait for either the GUI library I use to update an error out or for Paper to out 1.17. The moment one of these happens ill pop another snapshot up.

**Comment by Sefiraat** [comment]
Can you try downloading 1.1.5-SNAPSHOT once more. The GUI library has been updated and I have tested briefly and it all seems to work. Let me know how you get on please.

**Comment by thiccz1** [comment]
ok so the first time I used it with the updated gui lib it crashed but the second time i successfully opened it and have used it but now the condensate chest does not work anymore. Used to work like 15 min ago but just stopped working after i restarted my server

**Comment by thiccz1** [comment]
aslo spams this log https://pastebin.com/3NZyFfE1

**Comment by dixieland3** [comment]
for the test jar

**Comment by Sefiraat** [comment]
I have had some more time to look at this now and, @thiccz1 I cannot find an issue with either the Dissolution or Condensate chests in the Shapshot jar? Tested both before and after a restart with 1.16.5 and 1.17 items. Can you please try again and provide any error messages or a better description of what isnt working?

@dixieland3 In the releases part of this GitHub is a 1.1.5-SNAPSHOT which, from my testing works. Be sure to copy your EquivalencyTech config files somewhere safe (to be sure!) and use this. It should be a-ok!

**Comment by Sefiraat** [comment]
I've not heard back and all testing worked fine for me so I'll close this until I hear more from either of you.
