### ISSUE TITLE
[1.16.5] All items have no EMC values. No changes were made.

### ISSUE THREAD

**Issue by MagmaBro123** [Sefiraat/EquivalencyTech#5]
(Airplane is a fork of Tuinity (Can't spell it), which is a fork of Paper. Both have better performance.)
![2021-07-02_10 47 58](https://user-images.githubusercontent.com/51277766/124305740-55337380-db1a-11eb-853e-6a2dc297892d.png)
![2021-07-02_10 48 01](https://user-images.githubusercontent.com/51277766/124305747-5664a080-db1a-11eb-9dac-55d6f81d979e.png)

Pretty much everything has no EMC.
![2021-07-02_10 49 41](https://user-images.githubusercontent.com/51277766/124305938-9c216900-db1a-11eb-90db-99faae99a90f.png)
![2021-07-02_10 49 43](https://user-images.githubusercontent.com/51277766/124305940-9c216900-db1a-11eb-8564-296853fb0713.png)
![2021-07-02_10 49 46](https://user-images.githubusercontent.com/51277766/124305941-9cb9ff80-db1a-11eb-9470-61be4efeb01d.png)
![2021-07-02_10 49 49](https://user-images.githubusercontent.com/51277766/124305942-9cb9ff80-db1a-11eb-897b-a1ff57607846.png)

**Comment by Sefiraat** [comment]
Hi Magma,
I dont (and cant) add EMC to the items lore directly, if that was what you were expecting. Try using /et itememc when holding an item OR placing it inside your Transmutation Orb.

Sorry if you have tried these things, but the screenshots dont show that :)

**Comment by MagmaBro123** [comment]
EMC2 adds EMC to the item's lore if I'm correct.

**Comment by Sefiraat** [comment]
It does not. By adding EMC values to lore we would have to check every crafting, dropping or any other event that creates items a edit them. This would also break so many plugins that depend on items being in a specific form that, no, I will not be doing this. /et itememc or the Transmutation orb is more than enough.
