### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by itzTheMeow** [Sefiraat/EquivalencyTech#54]
Is this plugin dead? I really enjoy playing with it but it's a bit buggy on 1.18 or 1.19 and id love to see new features added.

Last commit was 8 months ago...

**Comment by MagmaSlime123** [comment]
This repo and Spigot page might as well be deleted.

**Comment by Sefiraat** [comment]
https://github.com/Sefiraat/EMCTech is the updated version of this addon. This addon will continue to receive support but only up to it’s supported versions.
