### ISSUE TITLE
[1.16.5] Server stalls.

### ISSUE THREAD

**Issue by MagmaBro123** [Sefiraat/EquivalencyTech#6]
Not really much to say.

Server is stuck here. Been 5 minutes.

No errors nor logs. Just the startup message. Restarted 3 times, same thing.

![image](https://user-images.githubusercontent.com/51277766/124311252-4d77cd00-db22-11eb-8ae3-84d82a302278.png)

(Airplane is a fork of Tuinity (Can't spell it), which is a fork of Paper. Both have better performance.)
![image](https://user-images.githubusercontent.com/51277766/124311333-6b453200-db22-11eb-8be8-e494d4c1cc8d.png)
![image](https://user-images.githubusercontent.com/51277766/124311357-726c4000-db22-11eb-9674-b60c5029d5c3.png)

**Comment by Sefiraat** [comment]
Can you try to run with DEGUB set to true in the config.yml? It looks like a recipe has got itself into a loop for some reason

**Comment by MagmaBro123** [comment]
Alright, hang on.

**Comment by MagmaBro123** [comment]
Not sure if 1.1.4 is for 1.17 or 1.16, but this is all I get.

https://pastebin.com/mwq6nybT
It's complaining about a bunch of missing 1.17x blocks/items.

**Comment by Sefiraat** [comment]
You are using 1.1.4. The release page very VERY clearly states that 1.1.5 is the release that supports 1.17 as so does the update history in spigot.
