### ISSUE TITLE
sf cheat

### ISSUE THREAD

**Issue by RIPISDRAD** [Sefiraat/EquivalencyTech#8]
hey there
EQuilivity tech does not support sf cheat at all not the book not the command of sf!
but u can duplicate it through the gmc and no other option i can think plz fix
more info: install the latest sf and and EQ and try sf cheat get some ingrediants then try to make sth with them it wont gives u and result

**Comment by Sefiraat** [comment]
ET items via /sf cheat will not work and, while not exactly indended it is working both as expected and required.
